name: 'master-stats-api-dev'

services:
  mongo:
    image: mongo:7.0.7
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: admin
    volumes:
      - mongodata:/etc/mongo
      - mongoconfig:/data/configdb
    network_mode: bridge
    ports:
      - 127.0.0.1:27017:27017

volumes:
  mongodata:
  mongoconfig: